[package]
name = "trash_can"
version = "0.1.0"
edition = "2024"

[dependencies]
cpu = {path = "cpu"}
assembler= {path = "assembler"}
compiler = {path = "compiler"}
tokio = { version = "1.47.1", features = ["full"] }
anyhow =  "1.0"
colog = "1.3"
log = "0.4"
minifb = "0.28.0"
