[package]
name = "trash_can"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.47.1", features = ["full"] }
lazy_static = "1.5"
eframe = {version ="0.32", features= [] }
anyhow =  "1.0"
colog = "1.3"
log = "0.4"
[env]
RUSTFLAGS = "-Awarnings"
